/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gt.edu.url.vista;

import gt.edu.url.clases.AbstractProduct;
import gt.edu.url.clases.Conexion;
import gt.edu.url.clases.ControladorProducto;
import gt.edu.url.clases.ProxyTblInventario;
import gt.edu.url.clases.ProxyTblVender;
import gt.edu.url.clases.Venta;
import gt.edu.url.controller.ClienteJpaController;
import gt.edu.url.controller.TipoProductoJpaController;
import gt.edu.url.entity.Producto;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Héctor Tello <hectortllo@gmail.com>
 */
public final class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    private Conexion conexion;
    private TipoProductoJpaController controllerTipoP;
    private ControladorProducto controllerProducto;
    private ClienteJpaController controllerCliente;
    private Venta venta;
    private String nombreUs;
    
    public FrmPrincipal(Conexion conexion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.conexion = conexion;
        controllerTipoP = new TipoProductoJpaController(this.conexion.getEntityManager());
        controllerProducto = new ControladorProducto();
        controllerCliente = new ClienteJpaController(this.conexion.getEntityManager());
        venta = new Venta(this.conexion.getEntityManager());
        getTipo();
    }

    public void setNombreUs(String nombreUs) {
        this.nombreUs = nombreUs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmInventario = new javax.swing.JPopupMenu();
        mOpciones = new javax.swing.JMenu();
        miOpciones = new javax.swing.JMenuItem();
        miDescripcion = new javax.swing.JMenuItem();
        pmVenta = new javax.swing.JPopupMenu();
        mOpcs = new javax.swing.JMenu();
        miEliminar = new javax.swing.JMenuItem();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlMenus = new javax.swing.JPanel();
        btnInventario = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        rsPnlPrincipal = new rojerusan.RSPanelsSlider();
        pnlAceitera = new javax.swing.JPanel();
        lblOccidente = new javax.swing.JLabel();
        lblAceitera = new javax.swing.JLabel();
        pnlInventario = new javax.swing.JPanel();
        lblInventario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new rojerusan.RSTableMetro();
        btnBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        cmbCategoria = new rojerusan.RSComboMetro();
        jLabel1 = new javax.swing.JLabel();
        btnIrVenta = new javax.swing.JButton();
        pnlVentas = new javax.swing.JPanel();
        lblVentas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVentas = new rojerusan.RSTableMetro();
        pnlVender = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVender = new rojerusan.RSTableMetro();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblNit = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        lbltotales = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblvueltos = new javax.swing.JLabel();
        lblVuelto = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        mOpciones.setText("Opciones");

        miOpciones.setText("Agregar a Venta");
        miOpciones.setContentAreaFilled(false);
        miOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpcionesActionPerformed(evt);
            }
        });
        mOpciones.add(miOpciones);

        miDescripcion.setText("Descipción");
        miDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDescripcionActionPerformed(evt);
            }
        });
        mOpciones.add(miDescripcion);

        pmInventario.add(mOpciones);

        mOpcs.setText("Opciones");

        miEliminar.setText("Eliminar Producto");
        miEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEliminarActionPerformed(evt);
            }
        });
        mOpcs.add(miEliminar);

        pmVenta.add(mOpcs);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenus.setBackground(new java.awt.Color(204, 255, 204));
        pnlMenus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInventario.setIcon(new javax.swing.ImageIcon("src/main/java/gt/edu/url/Imagenes/inventario.png"));
        btnInventario.setText("\n");
        btnInventario.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #FFA533;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Inventario</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnInventario.setBorder(null);
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.setFocusPainted(false);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        pnlMenus.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        btnVentas.setIcon(new javax.swing.ImageIcon("src/main/java/gt/edu/url/Imagenes/ventas.png"));
        btnVentas.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #FFA533;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Ventas</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnVentas.setBorder(null);
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setName("pnlVentas"); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        pnlMenus.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jPanel1.add(pnlMenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        pnlAceitera.setBackground(new java.awt.Color(255, 255, 204));
        pnlAceitera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOccidente.setBackground(new java.awt.Color(0, 0, 0));
        lblOccidente.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        lblOccidente.setForeground(new java.awt.Color(102, 102, 102));
        lblOccidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOccidente.setText("DE OCCIDENTE");
        pnlAceitera.add(lblOccidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 800, 90));

        lblAceitera.setBackground(new java.awt.Color(102, 102, 102));
        lblAceitera.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        lblAceitera.setForeground(new java.awt.Color(102, 102, 102));
        lblAceitera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAceitera.setText("ACEITERA");
        pnlAceitera.add(lblAceitera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 800, 90));

        rsPnlPrincipal.add(pnlAceitera, "card2");

        pnlInventario.setBackground(new java.awt.Color(255, 255, 204));
        pnlInventario.setName("pnlInventario"); // NOI18N
        pnlInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInventario.setBackground(new java.awt.Color(102, 102, 102));
        lblInventario.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblInventario.setForeground(new java.awt.Color(0, 153, 153));
        lblInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventario.setText("INVENTARIO");
        lblInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlInventario.add(lblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, 50));

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventario.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        tblInventario.setComponentPopupMenu(pmInventario);
        tblInventario.setRowHeight(25);
        jScrollPane1.setViewportView(tblInventario);
        if (tblInventario.getColumnModel().getColumnCount() > 0) {
            tblInventario.getColumnModel().getColumn(0).setResizable(false);
            tblInventario.getColumnModel().getColumn(1).setResizable(false);
            tblInventario.getColumnModel().getColumn(2).setResizable(false);
            tblInventario.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlInventario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 790, 430));

        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        pnlInventario.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, -1, -1));

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pnlInventario.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 320, -1));

        cmbCategoria.setColorArrow(new java.awt.Color(51, 0, 51));
        cmbCategoria.setColorBorde(new java.awt.Color(51, 0, 51));
        cmbCategoria.setColorFondo(new java.awt.Color(51, 0, 51));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        pnlInventario.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Categoría");
        pnlInventario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        btnIrVenta.setText("Ir a Venta");
        btnIrVenta.setEnabled(false);
        pnlInventario.add(btnIrVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, -1, -1));

        rsPnlPrincipal.add(pnlInventario, "card3");

        pnlVentas.setBackground(new java.awt.Color(255, 255, 204));
        pnlVentas.setForeground(new java.awt.Color(255, 255, 204));
        pnlVentas.setName("pnlVentas"); // NOI18N
        pnlVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVentas.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(0, 153, 153));
        lblVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentas.setText("VENTAS");
        lblVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlVentas.add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 880, 60));

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentas.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        tblVentas.setRowHeight(25);
        jScrollPane2.setViewportView(tblVentas);
        if (tblVentas.getColumnModel().getColumnCount() > 0) {
            tblVentas.getColumnModel().getColumn(0).setResizable(false);
            tblVentas.getColumnModel().getColumn(1).setResizable(false);
            tblVentas.getColumnModel().getColumn(2).setResizable(false);
            tblVentas.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlVentas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 810, 520));

        rsPnlPrincipal.add(pnlVentas, "card4");

        pnlVender.setBackground(new java.awt.Color(255, 255, 204));
        pnlVender.setName("pnlVender"); // NOI18N
        pnlVender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVender.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVender.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        tblVender.setComponentPopupMenu(pmVenta);
        tblVender.setRowHeight(25);
        jScrollPane3.setViewportView(tblVender);
        if (tblVender.getColumnModel().getColumnCount() > 0) {
            tblVender.getColumnModel().getColumn(0).setResizable(false);
            tblVender.getColumnModel().getColumn(1).setResizable(false);
            tblVender.getColumnModel().getColumn(2).setResizable(false);
            tblVender.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlVender.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 530, 320));

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre:");
        pnlVender.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccion.setText("Dirección:");
        pnlVender.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pnlVender.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 220, 40));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pnlVender.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 220, 40));

        lblNit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNit.setForeground(new java.awt.Color(0, 0, 0));
        lblNit.setText("NIT:");
        pnlVender.add(lblNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Aquí va la fecha");
        pnlVender.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 25, 190, 40));

        txtNit.setBackground(new java.awt.Color(255, 255, 255));
        txtNit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pnlVender.add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 73, 190, 40));

        btnValidar.setForeground(new java.awt.Color(0, 0, 0));
        btnValidar.setText("Validar");
        btnInventario.setIcon(new javax.swing.ImageIcon("src/main/java/gt/edu/url/Imagenes/validar.png"));
        btnValidar.setBorder(null);
        btnValidar.setBorderPainted(false);
        btnValidar.setContentAreaFilled(false);
        btnValidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        pnlVender.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 110, 40));

        lbltotales.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbltotales.setForeground(new java.awt.Color(0, 0, 0));
        lbltotales.setText("Total:");
        pnlVender.add(lbltotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("Aquí va el total");
        pnlVender.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 245, 180, 40));

        lblMonto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(0, 0, 0));
        lblMonto.setText("Monto:");
        pnlVender.add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        txtMonto.setBackground(new java.awt.Color(255, 255, 255));
        txtMonto.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        pnlVender.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 170, 40));

        lblvueltos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblvueltos.setForeground(new java.awt.Color(0, 0, 0));
        lblvueltos.setText("Vuelto:");
        pnlVender.add(lblvueltos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        lblVuelto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblVuelto.setForeground(new java.awt.Color(0, 0, 0));
        lblVuelto.setText("Aquí va el vuelto");
        pnlVender.add(lblVuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 180, 30));

        btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setBorder(null);
        btnInventario.setIcon(new javax.swing.ImageIcon("src/main/java/gt/edu/url/Imagenes/pagar.png"));
        btnFinalizar.setBorderPainted(false);
        btnFinalizar.setContentAreaFilled(false);
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        pnlVender.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 90, 60));

        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnInventario.setIcon(new javax.swing.ImageIcon("src/main/java/gt/edu/url/Imagenes/regresar.png"));
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlVender.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 90, 60));

        rsPnlPrincipal.add(pnlVender, "card6");

        jPanel1.add(rsPnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 880, 650));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        moverPanel(btnInventario, pnlInventario);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        moverPanel(btnVentas, pnlVentas);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println(conexion.desconectar());
    }//GEN-LAST:event_formWindowClosing

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        tblInventario.setModel(new ProxyTblInventario(controllerTipoP.mostrar(cmbCategoria.getSelectedIndex()+1)));
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void miDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDescripcionActionPerformed
        int seleccion = tblInventario.getSelectedRow();
        if (seleccion != -1) {
            String mensaje = (String) tblInventario.getModel().getValueAt(seleccion, 4);
            JOptionPane.showMessageDialog(null, mensaje);
        }
        
        
    }//GEN-LAST:event_miDescripcionActionPerformed

    private void miOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpcionesActionPerformed
        int seleccion[] = tblInventario.getSelectedRows();
        for(int i=0; i<seleccion.length; i++){
            if(seleccion[i] != -1){
                String cantidad = JOptionPane.showInputDialog("Ingrese cantidad", "Producto"+tblInventario.getModel().getValueAt(seleccion[i], 1));
                controllerProducto.addProducto(new gt.edu.url.clases.Producto((int)tblInventario.getModel().getValueAt(seleccion[i], 0), 
                        (String)tblInventario.getModel().getValueAt(seleccion[i], 1), 
                        (float)tblInventario.getModel().getValueAt(seleccion[i], 2)*Integer.parseInt(cantidad), 
                        Integer.parseInt(cantidad)));
            }
        }
        lblTotal.setText(""+controllerProducto.getPrecio());
        tblVender.setModel(new ProxyTblVender(controllerProducto.getProductos()));
        rsPnlPrincipal.setPanelSlider(1, pnlVender, RSPanelsSlider.DIRECT.UP);
        controllerProducto.imprimir();
    }//GEN-LAST:event_miOpcionesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        moverPanel(btnVentas, pnlInventario);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        if(txtNit.getText().length() != 0){
            List<Object> lista = controllerCliente.buscar(txtNit.getText());
            if(lista != null){
                txtNombre.setText(""+ lista.get(1));
                txtDireccion.setText(""+lista.get(2));
                
            } else
                JOptionPane.showMessageDialog(null, "El cliente no existe, por lo que se creará");
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        //Aquí va la venta
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void miEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEliminarActionPerformed
        System.out.println("Después de eliminar");
        int seleccion = tblVender.getSelectedRow();
        if(seleccion != -1){
            controllerProducto.removerProducto((AbstractProduct) controllerProducto.getProductos().get(seleccion));
        }
        lblTotal.setText(""+controllerProducto.getPrecio());
        tblVender.setModel(new ProxyTblVender(controllerProducto.getProductos()));
        controllerProducto.imprimir();
    }//GEN-LAST:event_miEliminarActionPerformed

    private void moverPanel(JButton boton, JPanel panel) {
        if (!boton.isSelected()) {
            btnInventario.setSelected(false);
            btnVentas.setSelected(false);
            btnRegresar.setSelected(false);
            btnValidar.setSelected(false);
            btnFinalizar.setSelected(false);
            btnBuscar.setSelected(false);
            btnIrVenta.setSelected(false);
            boton.setSelected(true);
            rsPnlPrincipal.setPanelSlider(1, panel, RSPanelsSlider.DIRECT.RIGHT);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnIrVenta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnVentas;
    private rojerusan.RSComboMetro cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAceitera;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOccidente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JLabel lblVuelto;
    private javax.swing.JLabel lbltotales;
    private javax.swing.JLabel lblvueltos;
    private javax.swing.JMenu mOpciones;
    private javax.swing.JMenu mOpcs;
    private javax.swing.JMenuItem miDescripcion;
    private javax.swing.JMenuItem miEliminar;
    private javax.swing.JMenuItem miOpciones;
    private javax.swing.JPopupMenu pmInventario;
    private javax.swing.JPopupMenu pmVenta;
    private javax.swing.JPanel pnlAceitera;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlMenus;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlVender;
    private javax.swing.JPanel pnlVentas;
    private rojerusan.RSPanelsSlider rsPnlPrincipal;
    private rojerusan.RSTableMetro tblInventario;
    private rojerusan.RSTableMetro tblVender;
    private rojerusan.RSTableMetro tblVentas;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void getTipo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addAll(controllerTipoP.findTipoProductoEntities());
        cmbCategoria.setModel(model);
    }

}
