/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gt.edu.url.vista;

import gt.edu.url.clases.Conexion;
import gt.edu.url.clases.Persona;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Héctor Tello <hectortllo@gmail.com>
 */
public class Login extends javax.swing.JFrame {

    private Persona persona;
    private FrmPrincipal frmPrincipal;
    private Conexion conexion;

    public Login(Conexion conexion) {
        initComponents();
        this.conexion = conexion;
        configuracion();
    }

    private void configuracion() {
        this.setLocationRelativeTo(null);
        lblImagen.setIcon(new ImageIcon("src/main/java/gt/edu/url/Imagenes/LOGIN.png"));
        txtUsuario.setBackground(new Color(0, 0, 0, 0));
        PswContrasenia.setBackground(new Color(0, 0, 0, 0));
        btnEntrar.setBackground(new Color(0, 0, 0, 0));
        persona = new Persona(this.conexion);
    }

    public void setFrmPrincipal(FrmPrincipal frmPrincipal) {
        this.frmPrincipal = frmPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        PswContrasenia = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setBorder(null);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 170, 30));

        PswContrasenia.setText("jPasswordField1");
        PswContrasenia.setBorder(null);
        getContentPane().add(PswContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 221, 160, 30));

        txtUsuario.setBorder(null);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 133, 170, 30));

        lblImagen.setIcon(new javax.swing.ImageIcon("src/gt/edu/url/Imagenes/LOGIN.png"));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if (this.persona.verificarLogin(txtUsuario.getText(), PswContrasenia.getText())) {
            frmPrincipal.setVisible(true);
            frmPrincipal.setNombreUs(txtUsuario.getText());
            this.dispose();
        } else {
            System.out.println("Error usuario/contrasenia incorrecta");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println(conexion.desconectar());
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PswContrasenia;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
